Update patch set 1
Patch Set 1:

I've been able to check that this patch works:
https://ci.linaro.org/view/tcwg-ci/job/tcwg-buildfarm-master-hetzner/1222/label=tcwg-x86_64-ex40,target=aarch64-none-elf/console

Then, I looked at gcc.log.xz in
ex40-01:/home/tcwg-buildslave/logs-master-bug-2011/tcwg-buildfarm-master-hetzner1222-latest/x86_64.aarch64-none-elf

And saw:
spawn -ignore SIGHUP /linaro/Foundation_Platformpkg/models/Linux64_GCC-4.7/Foundation_Platform --image /home/tcwg-buildslave/workspace/tcwg-buildfarm-master-hetzner/label
/tcwg-x86_64-ex40/target/aarch64-none-elf/_build/builds/x86_64-unknown-linux-gnu/aarch64-none-elf/gcc.git~linaro-gcc-5-branch-stage2/gcc/testsuite/gcc/20010124-1.x0 --qui
et
ERROR: cpu0.gicv3_cpu_if: Virtual LPIs can not be supported in GICv2 only mode. Defaulting virtual lpi support to false.

which indicates that the Foundation Model actually executed the code.

To my knowledge, this error message is harmless, and does not cause the test to exit with an error code.

Below this message, there other spurious messages from dejagnu, which would be fixed by the DJ patch I attached to bug #2011.

Patch-set: 1
Label: Code-Review=0